$wal_bg = rgb({background.strip})
$wal_fg = rgb({foreground.strip})

$wal0 = rgb({color0.strip})
$wal1 = rgb({color1.strip})
$wal2 = rgb({color2.strip})
$wal3 = rgb({color3.strip})
$wal4 = rgb({color4.strip})
$wal7 = rgb({color7.strip})
$wal8 = rgb({color8.strip})
